spring.datasource.url=jdbc:mariadb://mariadb_docker:3306/gameProyectodb
spring.datasource.username=svega
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Indicar que se ejecute schema.sql al iniciar
#spring.sql.init.mode=always
#spring.sql.init.schema-locations=classpath:schema.sql